# Creating a GitHub Actions Workflow to build and publish Replicon Handler.
# Uses build and twine to build and publish the package to PyPI.

# GitHub Actions Workflow Name
name: Publish Replicon Handler

# Actions Workflow runs when a new release is created
on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout latest code
      - name: Checkout code
        uses: actions/checkout@v2

      # Setting up Python Version
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9.7"

      # Installing Dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade build

      # Building Replicon Handler
      - name: Build Package
        run: python -m build

      # Publishing Replicon Handler
      - name: Publish Package
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
